- project:
    name: zuul-org/sample-project
    check:
      jobs:
        - noop
        - echo

- job:
    name: timeout
    run: timeout.yaml

- job:
    name: echo
    required-projects:
      - zuul-org/zuul-test
    run: echo.yaml
